- name: 'Deploy to Azure Static Web Apps'
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: upload
    app_location: "/"                  # or your folder with HTML files
    output_location: "."              # this is where your static files are
    skip_app_build: true              # <--- tells Oryx not to try building
